"""
Django settings for liliumpharm project.

Generated by 'django-admin startproject' using Django 3.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "i0u_vu&_=$70-1z+z4-x0mszk842klq75&6wjqt4^r_f874f^)"

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = bool(int(os.environ.get("DEBUG",0)))
DEBUG = True
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "medecins",
    "regions",
    "rapports",
    "produits",
    "accounts",
    "downloads",
    "orders",
    "plans",
    "clients",
    "rest_framework",
    "rest_framework.authtoken",
    "django_cleanup",
    "company",
    "notifications",
    "leaves",
    "deals",
    "concurents",
    "monthly_evaluations",
    "evaluations",
    "visite_duo",
    "application_user_manual",
    # "supervisors_evaluations",
    # "test",
    "depenses",
    "fournisseurs",
    "versement",
    "meet",
    "production",
    "deplacement"
    # "e-mail",
]

CORS_ORIGIN_ALLOW_ALL = True

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # 'rapports.middleware.BDDCON',
    "django.middleware.locale.LocaleMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "rapports.middleware.ProtectCommercial",
    # 'accounts.models.UserProxyMiddleWare',
]

ROOT_URLCONF = "liliumpharm.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "liliumpharm.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "HOST": "localhost",
        "NAME": "lilliumpharma",
        "USER": "postgres",
        "PASSWORD": "openpgpwd",
        "PORT":'6432',
        'CONN_MAX_AGE': 0,
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


USE_THOUSAND_SEPARATOR = False


JAZZMIN_SETTINGS = {
    "site_title": "Library Admin",
    "site_header": "Administration",
    # "hide_apps": ['robots'],
    "topmenu_links": [
        # Url that gets reversed (Permissions can be added)
        {"name": "Supervisor", "url": "/"},
        {"name": "My profile", "url": "/rapports/"},
    ],
    "icons": {
        "rapports.Rapport": "fas fa-clipboard-list",
        "rapports.Visite": "fas fa-clipboard-list",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "produits.Produit": "fas fa-industry",
        # "posts.Activity": "fab fa-buffer",
        "regions.Commune": "fa fa-globe",
        "regions.Wilaya": "fa fa-globe",
        "regions.Pays": "fa fa-globe",
        "cart.Cart": "fa fa-shopping-cart",
        "rapports.Comment": "fas fa-comment",
        "medecins.Medecin": "fas fa-user-md",
        "downloads.Downloadable": "fas fa-download",
    },
    "copyright": "Lilium Pharma",
}


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Etc/GMT-1"  #'SET'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LOCALE_PATHS = [os.path.join(BASE_DIR, "locale")]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static_original")]
STATIC_ROOT = os.path.join(BASE_DIR, "static")


MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
# MEDIA_ROOT='/home/lilium46/app.liliumpharma.com/media'

LOGIN_URL = "/accounts/login"
LOGIN_REDIRECT_URL = "HomeRapport"
LOGOUT_REDIRECT_URL = "login"


# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'


#EMAIL_HOST = "mail.liliumpharma.com"
#EMAIL_HOST_USER = "webmaster@liliumpharma.com"
#EMAIL_HOST_PASSWORD = "Webdev1993++"
#DEFAULT_FROM_EMAIL = "liliumpharma.com <webmaster@liliumpharma.com>"
#SERVER_EMAIL = "webmaster@liliumpharma.com"
#EMAIL_USE_TLS = True

LANGUAGES = [
    ("en", _("English")),
    ("fr", _("Français")),
    ("ar", _("Arabic")),
]


# AUTHENTICATION_BACKENDS=(
#     'accounts.backends.EmailBackend',
# )


JAZZMIN_SETTINGS["show_ui_builder"] = True


JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": True,
    "brand_small_text": False,
    "brand_colour": "navbar-primary",
    "accent": "accent-success",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-lime",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": True,
    "sidebar_nav_flat_style": True,
    "theme": "default",
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-outline-info",
        "warning": "btn-outline-warning",
        "danger": "btn-outline-danger",
        "success": "btn-outline-success",
    },
}


CKEDITOR_UPLOAD_PATH = "uploads"

#
# BASIC INITIAL VARRIABLES

DATETIME_INPUT_FORMATS = "%dd-%mm-%YYYY %H:%M:%S"

GOOGLE_RECAPTCHA_SECRET_KEY = "6LdZqLAZAAAAAIMDUFLupfowMQN2Eob7vw3OnpS2"

NOTIFICATION_CERTIFICATE = os.path.join(BASE_DIR, "notifications/secrets/firebase-service-account.json")


# EMAIL_HOST="mail.liliumpharma.com"
# EMAIL_PORT=465
# EMAIL_HOST_USER="rapports@liliumpharma.com"
# EMAIL_HOST_PASSWORD="Password123++@"

# EMAIL_USE_TLS=False
# EMAIL_USE_SSL=True
# EMAIL_TIMEOUT=
# EMAIL_SSL_KEYFILE=
# EMAIL_SSL_CERTFILE=


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_HOST_USER = "server.lilium@gmail.com"
EMAIL_HOST_PASSWORD = "ocnjhnwajtjjornv"  # past the key or password app here
EMAIL_PORT = 587
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = "server.lilium@gmail.com"


DEFAULT_AUTO_FIELD = "django.db.models.AutoField"

